Support for histogram file download
phraktle/histodiff pull request #1
Opened 2017-12-23 21:08 UTC by rsvoboda

Support for histogram file download.
Temporary file is deleted at the end

Usage examples:
```
java -jar histodiff-0.2.jar http://localhost:8000/foo.histo http://localhost:8000/bar.histo
java -jar histodiff-0.2.jar http://localhost:8000/foo.histo ~/tmp/bar.histo 0 150
```

2017-12-27 08:01 UTC, phraktle requested changes
Thanks for the contribution! I have added some comments, after which I'm happy to merge.

2017-12-27 08:01 UTC, phraktle commented on src/main/java/com/phraktle/histodiff/HistoDiff.java
> +            } catch (Exception e) {
Exceptions should not be caught here, declare as `throws` (as well as in `main`). Don't return `null`.

2017-12-27 08:01 UTC, phraktle commented on src/main/java/com/phraktle/histodiff/HistoDiff.java
> +        if (args[idx].startsWith("http")) {
A filename may also start with `http`. Make this more robust (e.g. include `://`).

2018-01-02 07:38 UTC, rsvoboda commented
PR updated, ready for review.

2018-01-02 08:40 UTC, merged

2018-01-02 08:40 UTC, phraktle commented
Merged, thank you!